name: This is my first ci/cd pipeline

on: 
  push:
    branches: main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Initialize Repo
        uses: actions/checkout@v6

      - name: Run echo
        run: echo "This is devops"
             uname a

      - name: Check docker installation
        run: |
          docker
          docker images

      - name: Run docker containner
        run: |
          docker run hello world
      
